name: 'sambaiz-test-docker-github-action'
description: 'Echo your word'
inputs:
  i-say:
    description: 'What do you say?'
    required: true
    default: '{}'
outputs:
  return-word:
    description: 'return word you said'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.i-say }}
